# Generated by tools/server/gen_gamedata.py -- do not edit by hand.
#
# Mirrors the tables the game compiles in, so the server scores hits with
# the same numbers the client renders.

GUNS = [
    {'id': 0, 'name': 'Knife', 'damage': 40, 'falloff': 1.0, 'pellets': 1, 'is_knife': True, 'price': 0, 'magazine': 0, 'max_ammo': 0, 'team': -1},
    {'id': 1, 'name': 'Glock-18', 'damage': 24, 'falloff': 0.75, 'pellets': 1, 'is_knife': False, 'price': 400, 'magazine': 20, 'max_ammo': 120, 'team': -1},
    {'id': 2, 'name': 'USP', 'damage': 29, 'falloff': 0.79, 'pellets': 1, 'is_knife': False, 'price': 500, 'magazine': 12, 'max_ammo': 100, 'team': -1},
    {'id': 3, 'name': 'P228', 'damage': 31, 'falloff': 0.8, 'pellets': 1, 'is_knife': False, 'price': 600, 'magazine': 13, 'max_ammo': 52, 'team': -1},
    {'id': 4, 'name': 'Desert Eagle', 'damage': 53, 'falloff': 0.81, 'pellets': 1, 'is_knife': False, 'price': 650, 'magazine': 7, 'max_ammo': 35, 'team': -1},
    {'id': 5, 'name': 'Dual Berettas', 'damage': 43, 'falloff': 0.75, 'pellets': 1, 'is_knife': False, 'price': 800, 'magazine': 30, 'max_ammo': 120, 'team': 0},
    {'id': 6, 'name': 'Five SeveN', 'damage': 24, 'falloff': 0.885, 'pellets': 1, 'is_knife': False, 'price': 750, 'magazine': 20, 'max_ammo': 100, 'team': 1},
    {'id': 7, 'name': 'M3', 'damage': 28, 'falloff': 0.7, 'pellets': 6, 'is_knife': False, 'price': 1700, 'magazine': 8, 'max_ammo': 48, 'team': -1},
    {'id': 8, 'name': 'XM1014', 'damage': 19, 'falloff': 0.7, 'pellets': 6, 'is_knife': False, 'price': 3000, 'magazine': 7, 'max_ammo': 32, 'team': -1},
    {'id': 9, 'name': 'M249', 'damage': 35, 'falloff': 0.97, 'pellets': 1, 'is_knife': False, 'price': 5750, 'magazine': 100, 'max_ammo': 200, 'team': -1},
    {'id': 10, 'name': 'MAC-10', 'damage': 28, 'falloff': 0.82, 'pellets': 1, 'is_knife': False, 'price': 1400, 'magazine': 30, 'max_ammo': 100, 'team': 0},
    {'id': 11, 'name': 'TMP', 'damage': 19, 'falloff': 0.85, 'pellets': 1, 'is_knife': False, 'price': 1250, 'magazine': 30, 'max_ammo': 120, 'team': 1},
    {'id': 12, 'name': 'MP5', 'damage': 25, 'falloff': 0.84, 'pellets': 1, 'is_knife': False, 'price': 1500, 'magazine': 30, 'max_ammo': 120, 'team': -1},
    {'id': 13, 'name': 'UMP-45', 'damage': 29, 'falloff': 0.75, 'pellets': 1, 'is_knife': False, 'price': 1250, 'magazine': 25, 'max_ammo': 100, 'team': -1},
    {'id': 14, 'name': 'P90', 'damage': 25, 'falloff': 0.885, 'pellets': 1, 'is_knife': False, 'price': 2350, 'magazine': 50, 'max_ammo': 100, 'team': -1},
    {'id': 15, 'name': 'FAMAS', 'damage': 29, 'falloff': 0.96, 'pellets': 1, 'is_knife': False, 'price': 2250, 'magazine': 25, 'max_ammo': 75, 'team': 1},
    {'id': 16, 'name': 'Galil', 'damage': 29, 'falloff': 0.98, 'pellets': 1, 'is_knife': False, 'price': 2000, 'magazine': 35, 'max_ammo': 90, 'team': 0},
    {'id': 17, 'name': 'AK-47', 'damage': 35, 'falloff': 0.98, 'pellets': 1, 'is_knife': False, 'price': 2500, 'magazine': 30, 'max_ammo': 90, 'team': 0},
    {'id': 18, 'name': 'Scout', 'damage': 74, 'falloff': 0.98, 'pellets': 1, 'is_knife': False, 'price': 2750, 'magazine': 10, 'max_ammo': 90, 'team': -1},
    {'id': 19, 'name': 'M4A1', 'damage': 31, 'falloff': 0.97, 'pellets': 1, 'is_knife': False, 'price': 3100, 'magazine': 30, 'max_ammo': 90, 'team': 1},
    {'id': 20, 'name': 'AUG', 'damage': 31, 'falloff': 0.96, 'pellets': 1, 'is_knife': False, 'price': 3500, 'magazine': 30, 'max_ammo': 90, 'team': 1},
    {'id': 21, 'name': 'SG 552', 'damage': 32, 'falloff': 0.955, 'pellets': 1, 'is_knife': False, 'price': 3500, 'magazine': 30, 'max_ammo': 90, 'team': 0},
    {'id': 22, 'name': 'SG 550', 'damage': 69, 'falloff': 0.98, 'pellets': 1, 'is_knife': False, 'price': 4200, 'magazine': 30, 'max_ammo': 90, 'team': 1},
    {'id': 23, 'name': 'AWP', 'damage': 115, 'falloff': 0.99, 'pellets': 1, 'is_knife': False, 'price': 4750, 'magazine': 10, 'max_ammo': 30, 'team': -1},
    {'id': 24, 'name': 'G3SG1', 'damage': 79, 'falloff': 0.98, 'pellets': 1, 'is_knife': False, 'price': 5000, 'magazine': 20, 'max_ammo': 90, 'team': 0},
]

# map id -> team (0 T, 1 CT) -> list of (x, y, z) world positions
SPAWNS = {
    0: {
        0: [(-3.0, 6.43, 65.0), (-6.0, 6.43, 65.0), (-9.0, 6.43, 65.0), (-3.0, 6.43, 62.5), (-6.0, 6.43, 62.5), (-9.0, 6.43, 62.5)],
        1: [(16.0, 0.0, -22.0), (19.5, 0.0, -22.0), (23.0, 0.0, -22.0), (16.0, 0.0, -19.5), (19.5, 0.0, -22.0), (23.0, 0.0, -22.0)],
    },
    1: {
        0: [(0.0, 0.0, 0.0)],
        1: [(0.0, 0.0, 0.0)],
    },
    2: {
        0: [(-3.0, 6.43, 65.0), (-6.0, 6.43, 65.0), (-9.0, 6.43, 65.0), (-3.0, 6.43, 62.5), (-6.0, 6.43, 62.5), (-9.0, 6.43, 62.5)],
        1: [(16.0, 0.0, -22.0), (19.5, 0.0, -22.0), (23.0, 0.0, -22.0), (16.0, 0.0, -19.5), (19.5, 0.0, -22.0), (23.0, 0.0, -22.0)],
    },
    3: {
        0: [(4.0, 0.0, 16.2), (-2.5, 0.0, 16.2), (12.0, 0.0, 16.2), (4.0, 0.0, 18.5), (-2.5, 0.0, 18.5), (12.0, 0.0, 18.5)],
        1: [(-3.7, 0.0, -15.44), (-11.82, 0.0, -15.44), (2.71, 0.0, -15.44), (-3.7, 0.0, -17.74), (-11.82, 0.0, -17.74), (2.71, 0.0, -17.74)],
    },
    4: {
        0: [(0.0, 0.0, -14.3), (-7.0, 0.0, -14.3), (7.0, 0.0, -14.3), (0.0, 0.0, -17.3), (-7.0, 0.0, -17.3), (7.0, 0.0, -17.3)],
        1: [(0.0, 0.0, 14.3), (-7.0, 0.0, 14.3), (7.0, 0.0, 14.3), (0.0, 0.0, 17.3), (-7.0, 0.0, 17.3), (7.0, 0.0, 17.3)],
    },
    5: {
        0: [(0.0, 0.0, -16.0), (-7.0, 0.0, -16.0), (7.0, 0.0, -16.0), (0.0, 0.0, -21.0), (-7.0, 0.0, -21.0), (7.0, 0.0, -21.0)],
        1: [(0.0, 0.0, 16.0), (-7.0, 0.0, 16.0), (7.0, 0.0, 16.0), (0.0, 0.0, 21.0), (-7.0, 0.0, 21.0), (7.0, 0.0, 21.0)],
    },
    6: {
        0: [(22.5, 2.45, 58.0), (25.0, 2.45, 58.0), (20.0, 2.45, 58.0), (22.5, 2.45, 61.0), (25.0, 2.45, 61.0), (20.0, 2.45, 61.0)],
        1: [(-22.5, 0.0, -10.0), (-20.0, 0.0, -10.0), (-25.0, 0.0, -10.0), (-22.5, 0.0, -14.0), (-20.0, 0.0, -14.0), (-25.0, 0.0, -14.0)],
    },
}
