#!/usr/bin/env python3
"""Generate gamedata.py from the game's C source.

The server needs the same weapon damage numbers and spawn points the client
compiles in. Extracting them rather than copying them by hand means editing
gun_data.c or map.c and re-running this keeps the server honest; a hand-copied
table would silently drift the first time a weapon is rebalanced.

Usage:  python3 tools/server/gen_gamedata.py
"""

from __future__ import annotations

import ast
import operator
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "Counter-Strike-nds" / "source"
GUN_DATA = SOURCE / "weapons" / "data" / "gun_data.c"
MAP_DATA = SOURCE / "map" / "map.c"
OUT = Path(__file__).resolve().parent / "gamedata.py"

TEAM = {"TERRORISTS": 0, "COUNTERTERRORISTS": 1, "BOTH": -1}
MAPS = {
    "DUST2": 0,
    "TUTORIAL": 1,
    "DUST2_2x2": 2,
    "AIM_MAP": 3,
    "B2000": 4,
    "FYSNOW": 5,
    "MIRAGE": 6,
}

_OPS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.USub: operator.neg,
}


def const_eval(text: str, defines: dict[str, float]):
    """Evaluate a C constant expression such as `171 / 6` or `LIGHT_SPEED`."""
    text = text.strip()
    if text in defines:
        return defines[text]
    if text in ("true", "false"):
        return text == "true"

    def walk(node):
        if isinstance(node, ast.Expression):
            return walk(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
            return node.value
        if isinstance(node, ast.Name) and node.id in defines:
            return defines[node.id]
        if isinstance(node, ast.BinOp) and type(node.op) in _OPS:
            return _OPS[type(node.op)](walk(node.left), walk(node.right))
        if isinstance(node, ast.UnaryOp) and type(node.op) in _OPS:
            return _OPS[type(node.op)](walk(node.operand))
        raise ValueError(text)

    try:
        return walk(ast.parse(text, mode="eval"))
    except Exception:
        return None


def parse_guns() -> list[dict]:
    src = GUN_DATA.read_text()
    defines = {
        name: float(value)
        for name, value in re.findall(r"#define\s+(\w+)\s+([0-9.]+)", src)
    }
    body = src[src.index("void LoadGuns()") :]
    guns = []
    for index, block in enumerate(body.split("gunIndex++;")[:-1]):

        def field(name):
            match = re.search(
                r"AllGuns\[gunIndex\]\.%s\s*=\s*([^;]+);" % name, block
            )
            return match.group(1).strip() if match else None

        def number(name, default=0):
            raw = field(name)
            if raw is None:
                return default
            value = const_eval(raw, defines)
            return default if value is None else value

        name = (field("name") or '"?"').strip().strip('"')
        guns.append(
            {
                "id": index,
                "name": name,
                # C truncates the integer division in `171 / 6`.
                "damage": int(number("Damage")),
                "falloff": float(number("DamageFalloff", 1.0)),
                "pellets": int(number("bulletCountPerShoot", 1)),
                "is_knife": field("isKnife") == "true",
                "price": int(number("Price", 0)),
                "magazine": int(number("MagazineCapacity", 0)),
                "max_ammo": int(number("MaxAmmoCount", 0)),
                "team": TEAM.get((field("team") or "BOTH").strip(), -1),
            }
        )
    return guns


def parse_spawns() -> dict[int, dict[int, list[tuple[float, float, float]]]]:
    src = MAP_DATA.read_text()
    spawns: dict[int, dict[int, list]] = {}
    pattern = re.compile(
        r"AddSpawnPoint\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\d+)\s*,\s*"
        r"(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\)"
    )
    for map_name, team_name, index, x, y, z in pattern.findall(src):
        map_id = MAPS.get(map_name)
        if map_id is None:
            continue
        # The tutorial map passes raw 0/1 rather than the team enum.
        team = TEAM.get(team_name)
        if team is None:
            try:
                team = int(team_name)
            except ValueError:
                continue
        slot = spawns.setdefault(map_id, {0: [], 1: []}).setdefault(team, [])
        slot.append((float(x), float(y), float(z)))
    return spawns


def main() -> None:
    guns = parse_guns()
    spawns = parse_spawns()

    lines = [
        "# Generated by tools/server/gen_gamedata.py -- do not edit by hand.",
        "#",
        "# Mirrors the tables the game compiles in, so the server scores hits with",
        "# the same numbers the client renders.",
        "",
        "GUNS = [",
    ]
    for gun in guns:
        lines.append("    %r," % (gun,))
    lines.append("]")
    lines.append("")
    lines.append("# map id -> team (0 T, 1 CT) -> list of (x, y, z) world positions")
    lines.append("SPAWNS = {")
    for map_id in sorted(spawns):
        lines.append("    %d: {" % map_id)
        for team in sorted(spawns[map_id]):
            points = spawns[map_id][team]
            if points:
                lines.append("        %d: %r," % (team, points))
        lines.append("    },")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print("wrote %s: %d guns, %d maps with spawns" % (OUT, len(guns), len(spawns)))
    for gun in guns:
        if gun["damage"] <= 0 and not gun["is_knife"]:
            print("  warning: %s has no damage" % gun["name"])


if __name__ == "__main__":
    main()
